name: setup
description: Sets up development environment
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    # spell-checker: disable-next-line
    - uses: swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
    - uses: homebrew/actions/setup-homebrew@master
      if: runner.os == 'macOS'
    # spell-checker: disable-next-line
    - run: echo PATH=/home/linuxbrew/.linuxbrew/bin:$PATH >> ${{ github.env }}
      shell: bash
    - run: tools/setup.sh
      shell: bash
