name: document
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: ./.github/actions/setup
      - run: cargo doc --all-features
      - run: rm target/doc/.lock
      - uses: actions/upload-pages-artifact@v4
        with:
          path: target/doc
      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
